#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $SKOOLDAZE_HOME ]]; then
  echo "Error: SKOOLDAZE_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLDAZE_HOME ]]; then
  echo "Error: directory not found: $SKOOLDAZE_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

GAME=sd
GAMEDIR=skool_daze
GAMENAME="Skool Daze"
SKOOLFILES=$(echo {sd,load,save,start}.skool)
SRCFILES=$(echo COPYING skooldaze.py sd{,-bugs,-changelog,-data,-facts,-glossary,-graphics,-pages,-pokes}.ref {sd,load,save,start}.skool sd{,-dark,-green,-plum}.css tiles.js)
DHOME=$SKOOLDAZE_HOME
GHREPO=skooldaze
GHHTMLOPTS=""

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
